[package]
name = "pippo"
version = "0.1.0"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
anyhow = "1"
chrono = "0.4"
futures-util = { version = "0.3.34", features = ["sink"] }
getrandom = "0.3"
ignore = "0.4"
keyring = "4.1.6"
regex = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
similar = "2"
tauri = { version = "2", features = [] }
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros", "sync"] }
tokio-tungstenite = "0.30.0"

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
strip = true
